### ISSUE TITLE
Failing database command when trying to delete a project

### ISSUE THREAD

**Issue by tlmrgvf** [ccims/ccims-backend-gql#45]
Running the query
```graphql
mutation{
  deleteProject(input: {project: "<Project ID>"}){
    clientMutationID
  }
}
```

fails at the backend:
```
...
server_1  | {
server_1  |   text: 'SELECT main.id, main.username, main.displayname, main.email, main.linked_user_id, main.pw_hash FROM ccims_user main  WHERE (main.id=$1)  ORDER BY main.id;',
server_1  |   values: [ '0' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT main.id, main.name, main.description FROM project main  WHERE (main.id=$1)  ORDER BY main.id;',
server_1  |   values: [ '5eaab9c3e2a1b006' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT main.id, main.deleted, main.created_by_id, main.created_at, main.name, main.description, main.last_updated_at, main.repository_url, main.last_modified_at FROM component main  WHERE (main.id=ANY(SELECT component_id FROM relation_project_component WHERE project_id=$1))  ORDER BY main.id;',
server_1  |   values: [ '5eaab9c3e2a1b006' ]
server_1  | }
db_1      | 2021-07-15 16:02:06.887 UTC [139] ERROR:  column main.component_id does not exist at character 686
db_1      | 2021-07-15 16:02:06.887 UTC [139] STATEMENT:  SELECT main.id, main.deleted, main.created_by_id, main.created_at, main.title, main.is_open, main.is_duplicate, main.category, main.start_date, main.due_date, main.estimated_time, main.spent_time, main.last_updated_at, main.priority, main.body_id, main.last_modified_at, body.deleted AS body_deleted, body.created_by_id AS body_created_by_id, body.created_at AS body_created_at, body.issue_id AS body_issue_id, body.body AS body_body, body.last_edited_at AS body_last_edited_at, body.last_edited_by_id AS body_last_edited_by_id, body.initial_title AS body_initial_title, body.last_modified_at AS body_last_modified_at FROM issue main LEFT JOIN body ON (main.body_id = body.id)  WHERE (main.component_id=ANY(SELECT component_id FROM relation_project_component WHERE project_id=$1))  ORDER BY main.id;
server_1  | {
server_1  |   text: 'SELECT main.id, main.deleted, main.created_by_id, main.created_at, main.title, main.is_open, main.is_duplicate, main.category, main.start_date, main.due_date, main.estimated_time, main.spent_time, main.last_updated_at, main.priority, main.body_id, main.last_modified_at, body.deleted AS body_deleted, body.created_by_id AS body_created_by_id, body.created_at AS body_created_at, body.issue_id AS body_issue_id, body.body AS body_body, body.last_edited_at AS body_last_edited_at, body.last_edited_by_id AS body_last_edited_by_id, body.initial_title AS body_initial_title, body.last_modified_at AS body_last_modified_at FROM issue main LEFT JOIN body ON (main.body_id = body.id)  WHERE (main.component_id=ANY(SELECT component_id FROM relation_project_component WHERE project_id=$1))  ORDER BY main.id;',
server_1  |   values: [ '5eaab9c3e2a1b006' ]
server_1  | }
server_1  | database command failed
server_1  | error: column main.component_id does not exist
server_1  |     at Parser.parseErrorMessage (/home/node/app/node_modules/pg-protocol/dist/parser.js:287:98)
server_1  |     at Parser.handlePacket (/home/node/app/node_modules/pg-protocol/dist/parser.js:126:29)
server_1  |     at Parser.parse (/home/node/app/node_modules/pg-protocol/dist/parser.js:39:38)
server_1  |     at Socket.<anonymous> (/home/node/app/node_modules/pg-protocol/dist/index.js:11:42)
server_1  |     at Socket.emit (events.js:315:20)
server_1  |     at addChunk (internal/streams/readable.js:309:12)
server_1  |     at readableAddChunk (internal/streams/readable.js:284:9)
server_1  |     at Socket.Readable.push (internal/streams/readable.js:223:10)
server_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
server_1  |   length: 116,
server_1  |   severity: 'ERROR',
server_1  |   code: '42703',
server_1  |   detail: undefined,
server_1  |   hint: undefined,
server_1  |   position: '686',
server_1  |   internalPosition: undefined,
server_1  |   internalQuery: undefined,
server_1  |   where: undefined,
server_1  |   schema: undefined,
server_1  |   table: undefined,
server_1  |   column: undefined,
server_1  |   dataType: undefined,
server_1  |   constraint: undefined,
server_1  |   file: 'parse_relation.c',
server_1  |   line: '3514',
server_1  |   routine: 'errorMissingColumn'
server_1  | }
server_1  | {
server_1  |   text: 'DELETE FROM project WHERE id=$1',
server_1  |   values: [ '5eaab9c3e2a1b006' ]
server_1  | }
```

because column `component_id` does not exist in the database.
I am not sure if I set up the database correctly, it's missing in mine.

**Comment by nk-coding** [comment]
fixed with 403bc9205c3631c4bb624aa7b43f197155d29689
