### ISSUE TITLE
Problem creating new component

### ISSUE THREAD

**Issue by tlmrgvf** [ccims/ccims-backend-gql#46]
Running the query
```graphql
mutation{
  createComponent(input: {name: "a", description: "b", repositoryURL: "c", projects: ["<Project ID>"]}) {
    component {
      id
      imsComponents {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
```
fails with the error:

```
server_1  | {
server_1  |   text: 'SELECT main.id, main.username, main.displayname, main.email, main.linked_user_id, main.pw_hash FROM ccims_user main  WHERE (main.id=$1)  ORDER BY main.id;',
server_1  |   values: [ '0' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT main.id, main.name, main.description FROM project main  WHERE (main.id=$1)  ORDER BY main.id;',
server_1  |   values: [ '5eabe10d81e3b002' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT project_id, component_id FROM relation_project_component WHERE component_id=$1;',
server_1  |   values: [ '5eabe11b35a3b003' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT project_id, component_id FROM relation_project_component WHERE project_id=$1;',
server_1  |   values: [ '5eabe10d81e3b002' ]
server_1  | }
server_1  | {
server_1  |   text: 'INSERT INTO component (id, deleted, created_by_id, created_at, name, description, last_updated_at, repository_url) VALUES ($1, $2, $3, $4, $5, $6, $7, $8);',
server_1  |   values: [
server_1  |     '5eabe11b35a3b003',
server_1  |     false,
server_1  |     '0',
server_1  |     2021-07-16T13:32:09.302Z,
server_1  |     'a',
server_1  |     'a',
server_1  |     2021-07-16T13:32:09.302Z,
server_1  |     'a'
server_1  |   ]
server_1  | }
server_1  | {
server_1  |   text: 'INSERT INTO relation_project_component (project_id, component_id) VALUES ($1, $2) ON CONFLICT DO NOTHING;',
server_1  |   values: [ '5eabe10d81e3b002', '5eabe11b35a3b003' ]
server_1  | }
server_1  | {
server_1  |   text: 'SELECT id from ims_user WHERE ims_system_id = $1',
server_1  |   values: [ '5eabe11b35a3b003' ]
server_1  | }
db_1      | 2021-07-16 13:32:09.314 UTC [96] ERROR:  column "ims_system_id" does not exist at character 31
db_1      | 2021-07-16 13:32:09.314 UTC [96] STATEMENT:  SELECT id from ims_user WHERE ims_system_id = $1
server_1  | database command failed
server_1  | error: column "ims_system_id" does not exist
server_1  |     at Parser.parseErrorMessage (/home/node/app/node_modules/pg-protocol/dist/parser.js:287:98)
server_1  |     at Parser.handlePacket (/home/node/app/node_modules/pg-protocol/dist/parser.js:126:29)
server_1  |     at Parser.parse (/home/node/app/node_modules/pg-protocol/dist/parser.js:39:38)
server_1  |     at Socket.<anonymous> (/home/node/app/node_modules/pg-protocol/dist/index.js:11:42)
server_1  |     at Socket.emit (events.js:315:20)
server_1  |     at addChunk (internal/streams/readable.js:309:12)
server_1  |     at readableAddChunk (internal/streams/readable.js:284:9)
server_1  |     at Socket.Readable.push (internal/streams/readable.js:223:10)
server_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
server_1  |   length: 113,
server_1  |   severity: 'ERROR',
server_1  |   code: '42703',
server_1  |   detail: undefined,
server_1  |   hint: undefined,
server_1  |   position: '31',
server_1  |   internalPosition: undefined,
server_1  |   internalQuery: undefined,
server_1  |   where: undefined,
server_1  |   schema: undefined,
server_1  |   table: undefined,
server_1  |   column: undefined,
server_1  |   dataType: undefined,
server_1  |   constraint: undefined,
server_1  |   file: 'parse_relation.c',
server_1  |   line: '3514',
server_1  |   routine: 'errorMissingColumn'
server_1  | }
server_1  | {
server_1  |   text: 'SELECT main.id, main.name, main.description FROM project main  WHERE (main.id=$1)  ORDER BY main.id;',
server_1  |   values: [ '5eabe10d81e3b002' ]
server_1  | }
```

whereas
```graphql
mutation{
	createComponent(input: {name: "a", description: "b", repositoryURL: "c", projects: ["5eabe10d81e3b002"]}) {
    component {
      id
    }
  }
}
```

works without any issues

**Comment by nk-coding** [comment]
fixed with 2c2164b45908fa42899f3d1a0cbda87988b4675b
creating IMSSystem and IMSComponent should now also work
